### ISSUE TITLE
登录的数据库和密码指哪个数据库和密码？

### ISSUE THREAD

**Issue by tiansiyuan** [ningyile/BDMCC_APP#1]
<img width="794" alt="Screenshot 2023-12-18 at 20 59 23" src="https://github.com/ningyile/BDMCC_APP/assets/228619/7da79824-0fbc-4264-92e4-d5b6172b5314">

**Comment by ningyile** [comment]
你好。安装前请认真查看PostgreSQL和BDMCC的安装视频教程，请单击教程链接前往观看: https://www.bilibili.com/video/BV1Kc411q7g7/?vd_source=bf0edee2bc28836d99f5d19fd28d2225
教程前7分钟为通用部分，所有系统的用户都要观看，后面可根据自己系统在视频下方第一条评论单击时间戳跳转至相应的位置。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tian Siyuan ***@***.***&gt;
发送时间: 2023年12月18日 21:00
收件人: ningyile/BDMCC_APP ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ningyile/BDMCC_APP] 登录的数据库和密码指哪个数据库和密码？ (Issue #1)





 Screenshot.2023-12-18.at.20.59.23.png (view on web)

**Comment by ningyile** [comment]
你好。对应的是PostgreSQL的数据用户名和密码。如有未尽事宜，请详细观看B站视频教程。

安装前请认真查看PostgreSQL和BDMCC的安装视频教程，请单击教程链接前往观看: https://www.bilibili.com/video/BV1Kc411q7g7/?vd_source=bf0edee2bc28836d99f5d19fd28d2225
教程前7分钟为通用部分，所有系统的用户都要观看，后面可根据自己系统在视频下方第一条评论单击时间戳跳转至相应的位置。

![一键空降](https://github.com/ningyile/BDMCC_APP/assets/39246108/be8b6012-a9a7-4aba-bf54-fedba2340eba)

**Comment by tiansiyuan** [comment]
你好。

B站上的视频看过了。

视频提到，在 macOS 上是不需要密码的。

但是在我的安装上，不输入密码是不行的。

我特意运行了 `ALTER USER siyuant WITH PASSWORD 'Password';`之后，输入这个密码也不行。

**Comment by tiansiyuan** [comment]
"数据库名称"是不是误导了？应该是"数据库用户名"？

**Comment by ningyile** [comment]
> 你好。
> 
> B站上的视频看过了。
> 
> 视频提到，在 macOS 上是不需要密码的。
> 
> 但是在我的安装上，不输入密码是不行的。
> 
> 我特意运行了 `ALTER USER siyuant WITH PASSWORD 'Password';`之后，输入这个密码也不行。

你好，macOS不需要密码的前提是你安装了[Postgres.app](https://postgresapp.com/)这个应用，这个应用默认安装的HBA模式（对应的设置文件的路径为`/Users/XXXXXX/Library/Application Support/Postgres/var-16/pg_hba.conf`）是`trust`（如下图），所以此时不需要密码。但是如果你在你的macOS设备安装的是官方的或者源码编译的PostgreSQL，此时并不能保证你的模式是trust，很可能是`MD5`或者`SHA256`等加密模式，那么此时你就需要：
1. 在BDMCC中设置你正确的用户名和密码（在终端中使用`psql -U siyuanant`命令确认该密码是否正确）。
**或者**
2. 将pg_hba.conf设置的method改为`trust`，然后再重启psql的service使最新设置生效，然后**关闭并重新打开BDMCC软件**即可。

![hba](https://github.com/ningyile/BDMCC_APP/assets/39246108/a4e8b9d3-f2b0-4809-9bef-9b6d3f61d246)

**Comment by ningyile** [comment]
> "数据库名称"是不是误导了？应该是"数据库用户名"？

确实是容易造成误解，V1.0.2会更新这个label。不过期初这里设计的初衷是提醒用户，你的`PG数据库名称`是否含有一个和`数据库用户`*同名*的数据库？PG在psql交互终端的逻辑是这样的，假如你只输入`psql`命令，那么psql终端会自动帮你传入你的用户名作为`-U`（用户名）和`-d`（数据库名）的参数，例如假如您的macOS设备的用户名是`siyuanant`，那么在输入`psql`命令的时候会自动传入两个参数至`-U`和`-d`，即`psql -U siyuanant -d siyuanant`，假如你的PG数据库刚好有这个数据库用户`siyuanant`和对应模板数据库template生成的名为`siyuanant`的数据库，那么一切都会运行正常。但是假如两者缺乏一个，终端就会提示你，对应名为`siyuanant`的用户或者数据库不存在，那么此时你就没有办法用`psql`这个简短的命令了（这个命令可以使用的前提就是必须要有和macOS用户名相同的数据库用户和）。

同理，你在BDMCC软件上输入了你的用户名`siyuanant`，此时相当于传递两个参数，一个是`-U`，一个是给`-d`，只有两者都存在方可登录成功。如前面所说，你前面登录不成功的原因可能是这个（假如`siyuanant`的数据库用户名或者数据库名不存在，创建对应的即可）。所以我建议用户使用默认的`postgres`，因为在数据库默认安装的时候，无论是Windows、macOS还是Linux，所有的初始化结束后均会含有一个名为`postgres`的数据库用户和数据库，以提供是否登录成功的消息提示。因为写三个参数（用户名、数据库名、密码）怕用户懵，所以简写了两个。不过之后还是会按照你的建议改为数据库用户名。

查看已安装数据库名称最简单的方法就是在Postgres.app中查看，或者在psql交互终端中使用`\l`命令(是L的小写，代表list，并非1234的1)。

写的有点长，不知道你能不能绕得过来。如果你还是无法使用，微信联系我吧，我远程todesk帮你看看。

**在Postgres.app中查看数据库名称含有系统用户名对应的值**
![db_list_2](https://github.com/ningyile/BDMCC_APP/assets/39246108/d83cd6e4-3dd2-4af0-9a99-8f8a1e7de5f9)

**在终端中查看数据库名称含有系统用户名对应的值**
![db_list_1](https://github.com/ningyile/BDMCC_APP/assets/39246108/9180e47a-30f8-4621-afba-48dc01e13167)

**Comment by tiansiyuan** [comment]
> > 你好。
> > B站上的视频看过了。
> > 视频提到，在 macOS 上是不需要密码的。
> > 但是在我的安装上，不输入密码是不行的。
> > 我特意运行了 `ALTER USER siyuant WITH PASSWORD 'Password';`之后，输入这个密码也不行。
> 
> 你好，macOS不需要密码的前提是你安装了[Postgres.app](https://postgresapp.com/)这个应用，这个应用默认安装的HBA模式（对应的设置文件的路径为`/Users/XXXXXX/Library/Application Support/Postgres/var-16/pg_hba.conf`）是`trust`（如下图），所以此时不需要密码。但是如果你在你的macOS设备安装的是官方的或者源码编译的PostgreSQL，此时并不能保证你的模式是trust，很可能是`MD5`或者`SHA256`等加密模式，那么此时你就需要：
> 
> 1. 在BDMCC中设置你正确的用户名和密码（在终端中使用`psql -U siyuanant`命令确认该密码是否正确）。
>    **或者**
> 2. 将pg_hba.conf设置的method改为`trust`，然后再重启psql的service使最新设置生效，然后**关闭并重新打开BDMCC软件**即可。
> 
> ![hba](https://private-user-images.githubusercontent.com/39246108/291460455-a4e8b9d3-f2b0-4809-9bef-9b6d3f61d246.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODI0NTAsIm5iZiI6MTcwMjk4MjE1MCwicGF0aCI6Ii8zOTI0NjEwOC8yOTE0NjA0NTUtYTRlOGI5ZDMtZjJiMC00ODA5LTliZWYtOWI2ZDNmNjFkMjQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YTI4ZDY2YTU2ZjJjODEyMjdiYjliMWQxNGYzYmRlN2UxMTAxYTUwZmM0MzExMWZjZmE1NjE0N2I5MTVkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ePNtzuOtCHX1DTdPwhJC4iFJt02y7wZFWAmd9nJW6eY)

我是用 `brew` 安装的 `postgresql@16`。

我在 `/usr/local/var/postgresql@16` 目录下找到了 `pg_hba.conf`，里面的内容和你提到的一致：

```sh
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust
```

我安装 `Postgres.app` 试试。

**Comment by tiansiyuan** [comment]
安装 `Postgres.app` 后，可以了。
