### ISSUE TITLE
请问安装完，打开BDMCC，提示意外退出，怎么办

### ISSUE THREAD

**Issue by malatang2021** [ningyile/BDMCC_APP#2]
<img width="1039" alt="截屏2024-03-11 14 58 12" src="https://github.com/ningyile/BDMCC_APP/assets/91351982/aac345b9-71a8-4ffd-aa25-a58200895532">

**Comment by ningyile** [comment]
- 先安装brew，通过[Homebrew国内源](https://gitee.com/cunkai/HomebrewCN)安装brew，macOS的终端安装代码是
```

/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"

```

安装完毕后根据终端提示设置brew的环境变量的zshrc。

- brew安装完成后，使用brew安装openssl，终端代码是
```
brew install openssl
```


- homebrew安装的前提是你的macOS已经安装了Xcode开发环境或者Command Line Tools（CLT）。建议安装CLT，因为所需体积比较小，只有500MB左右。Command Line Tools 是一个小型独立包，为mac终端用户提供了许多常用的工具，实用程序和编译器，包括svn，git，make，GCC，clang等等。因为需要安装brew需要CLT工具编译源码为可执行的二进制文件。

- [【easyBDCC课程之第1章06：macOS下R的安装以及ODBC驱动设置-哔哩哔哩】 ](https://b23.tv/Z8EZHJT)的4分09至5分36秒即为Homebrew的安装视频教程，可进行参考。安装过程如有进一步困难可联系我帮你解决。
